# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dschlaepfer/projects/stapferhaus/geschlecht/godot-webcam

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dschlaepfer/projects/stapferhaus/geschlecht/godot-webcam

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dschlaepfer/projects/stapferhaus/geschlecht/godot-webcam/CMakeFiles /home/dschlaepfer/projects/stapferhaus/geschlecht/godot-webcam//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dschlaepfer/projects/stapferhaus/geschlecht/godot-webcam/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named godot_webcam

# Build rule for target.
godot_webcam: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 godot_webcam
.PHONY : godot_webcam

# fast build rule for target.
godot_webcam/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godot_webcam.dir/build.make CMakeFiles/godot_webcam.dir/build
.PHONY : godot_webcam/fast

#=============================================================================
# Target rules for targets named godot-cpp

# Build rule for target.
godot-cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 godot-cpp
.PHONY : godot-cpp

# fast build rule for target.
godot-cpp/fast:
	$(MAKE) $(MAKESILENT) -f godot-cpp/CMakeFiles/godot-cpp.dir/build.make godot-cpp/CMakeFiles/godot-cpp.dir/build
.PHONY : godot-cpp/fast

src/init.o: src/init.cpp.o

.PHONY : src/init.o

# target to build an object file
src/init.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godot_webcam.dir/build.make CMakeFiles/godot_webcam.dir/src/init.cpp.o
.PHONY : src/init.cpp.o

src/init.i: src/init.cpp.i

.PHONY : src/init.i

# target to preprocess a source file
src/init.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godot_webcam.dir/build.make CMakeFiles/godot_webcam.dir/src/init.cpp.i
.PHONY : src/init.cpp.i

src/init.s: src/init.cpp.s

.PHONY : src/init.s

# target to generate assembly for a file
src/init.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godot_webcam.dir/build.make CMakeFiles/godot_webcam.dir/src/init.cpp.s
.PHONY : src/init.cpp.s

src/webcam.o: src/webcam.cpp.o

.PHONY : src/webcam.o

# target to build an object file
src/webcam.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godot_webcam.dir/build.make CMakeFiles/godot_webcam.dir/src/webcam.cpp.o
.PHONY : src/webcam.cpp.o

src/webcam.i: src/webcam.cpp.i

.PHONY : src/webcam.i

# target to preprocess a source file
src/webcam.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godot_webcam.dir/build.make CMakeFiles/godot_webcam.dir/src/webcam.cpp.i
.PHONY : src/webcam.cpp.i

src/webcam.s: src/webcam.cpp.s

.PHONY : src/webcam.s

# target to generate assembly for a file
src/webcam.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godot_webcam.dir/build.make CMakeFiles/godot_webcam.dir/src/webcam.cpp.s
.PHONY : src/webcam.cpp.s

src/webcamV4L2.o: src/webcamV4L2.cpp.o

.PHONY : src/webcamV4L2.o

# target to build an object file
src/webcamV4L2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godot_webcam.dir/build.make CMakeFiles/godot_webcam.dir/src/webcamV4L2.cpp.o
.PHONY : src/webcamV4L2.cpp.o

src/webcamV4L2.i: src/webcamV4L2.cpp.i

.PHONY : src/webcamV4L2.i

# target to preprocess a source file
src/webcamV4L2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godot_webcam.dir/build.make CMakeFiles/godot_webcam.dir/src/webcamV4L2.cpp.i
.PHONY : src/webcamV4L2.cpp.i

src/webcamV4L2.s: src/webcamV4L2.cpp.s

.PHONY : src/webcamV4L2.s

# target to generate assembly for a file
src/webcamV4L2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godot_webcam.dir/build.make CMakeFiles/godot_webcam.dir/src/webcamV4L2.cpp.s
.PHONY : src/webcamV4L2.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... godot-cpp"
	@echo "... godot_webcam"
	@echo "... src/init.o"
	@echo "... src/init.i"
	@echo "... src/init.s"
	@echo "... src/webcam.o"
	@echo "... src/webcam.i"
	@echo "... src/webcam.s"
	@echo "... src/webcamV4L2.o"
	@echo "... src/webcamV4L2.i"
	@echo "... src/webcamV4L2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

